export const TOAST_MESSAGE = {
   FAILED_FETCH_COMPANIES : "Failed to fetch companies", 
   FAILED_LOAD_COMPANIES : "Failed to load companies", 
   UNPUBLISHED : "Unpublished", 
   APPROVED : "Potrjeno", 
   SOMETHING_WENT_WRONG : "Something went wrong, Please try later!",
   FAILED_LOAD_CONTACTS : "Failed to load contacts",
   FAILED_TO_LOAD_FINANCIAL_DATA : "Failed to load financial data",
   FAILED_TO_LOAD_FLORIST_COMPANIES_DATA : "Failed to load florist companies data",
   PERMISSIONS_UPDATED_SUCCESSFULLY : "Posodobljeno",
   FAILED_TO_UPDATED_PERMISSIONS : "Failed to update permissions",
   FAILED_TO_BLOCK_UNBLOCK_USER : "Failed to block/unblock user",
   NOTES_UPDATED_SUCCESSFULLY : "Posodobljeno",
   FAILED_TO_UPDATE_NOTES : "Failed to update notes",
   RATING_UPDATED_SUCCESSFULLY : "Posodobljeno",
   FAILED_TO_UPDATE_RATING : "Failed to update rating",
   FLORIST_STATUS_UPDATED_SUCCESSFULLY : "Posodobljeno",
   FAILED_TO_UPDATE_FLORIST_STATUS : "Failed to update florist status",
   PAYMENT_STATUS_UPDATED_SUCCESSFULLY : "Posodobljeno",
   FAILED_TO_UPDATE_PAYMENT_STATUS : "Failed to update payment status",
   FAILED_TO_LOAD_FUNERAL_COMPANIES_DATA : "Failed to load funeral companies data",
   OBITUARY_DELETED_SUCCESSFULLY_RECOVER_WITHIN_MONTH : "Obituary deleted successfully. It can be recovered within 1 month.",
   FAILED_TO_DELETE_OBITUARY : "Failed to delete obituary",
   OBITUARY_UNHIDDEN_SUCCESSFULLY : "Obituary unhidden successfully",
   OBITUARY_HIDDEN_SUCCESSFULLY : "Obituary hidden successfully",
   FAILED_TO_TOGGLE_OBITUARY_VISIBILITY : "Failed to toggle obituary visibility",
   MEMORY_PAGE_UNBLOCKED_SUCCESSFULLY : "Memory page unblocked successfully",
   MEMORY_PAGE_BLOCKED_SUCCESSFULLY : "Memory page blocked successfully",
   FAILED_TO_TOGGLE_MEMORY_VISIBILITY : "Failed to toggle memory visibility",
   ADMIN_NOTES_UPDATED_SUCCESSFULLY : "Admin notes updated successfully",
   FAILED_TO_UPDATE_ADMIN_NOTES : "Failed to update admin notes",
   FAILED_TO_LOAD_USERS : "Failed to load users",
   USER_UNBLOCKED_SUCCESSFULLY : "User unblocked successfully",
   USER_BLOCKED_SUCCESSFULLY : "User blocked successfully",
   USER_DELETED_SUCCESSFULLY : "User deleted successfully",
   FAILED_TO_DELETE_USER : "Failed to delete user",
   CITY_UPDATED_AND_SESSION_REFRESHED : "Posodobljeno",
   FLORIST_SHOP_DELETED_SUCCESSFULLY : "Florist shop deleted successfully.",
   ERROR_DELETING_FLORIST_SHOP : "Prišlo je do napake. Cvetličarna ni bila izbrisana.",
   CHANGES_APPLIED_SUCCESSFULLY : "Posodobljeno",
   COMPANY_IS_CREATED : "Dodano",
   ADD_ATLEAST_ONE_OFFER : "Dodajte vsaj eno ponudbo",
   DATA_SAVED : "Shranjeno",
   DATA_NOT_SAVED_TRY_AGAIN : "Podatki niso shranjeni. Poskusite znova.",
   YOU_CAN_ADD_4_PACKAGES : "Dodate lahko največ 4 paketov",
   PACKAGES_UPDATED_SUCCESSFULLY : "Posodobljeno",
   COMPANY_UPDATED_SUCCESSFULLY : "Posodobljeno",
   FAILED_TO_UPDATE_COMPANY_TRY_AGAIN : "Prišlo je do napake. Ni bilo posodobljeno. Poskusi znova.",
   COMPANY_NOT_READY_TRY_AGAIN : "Company is not ready. Please try again in a moment.",
   FLORIST_SLIDES_UPDATED_SUCCESSFULLY : "Posodobljeno",
   SHOP_DELETED_SUCCESSFULLY : "Shop deleted successfully.",
   ERROR_DELETING_FLORIST_SLIDES : "Error deleting florist slide.",
   ENTER_ALL_STORE_DATA : "Vpišite vse podatke o trgovini",
   SENT_FOR_APPROVAL : "Poslano v potrditev",
}